---
domain_name: "nas.lan"
nameservers:
  - ns1.nas.lan.
  - ns2.nas.lan.
traefik_ip: "{{ ansible_default_ipv4.address }}"
ttl: 86400
# Automatic generation of serial number (format: YYYYMMDDSS)
soa_serial: "{{ (ansible_date_time.date | replace('-', '') + ansible_date_time.second) | int }}"
services: []