version: "3.7"

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --dns.nameservers=127.0.0.1
    ports:
      - 80:80
      - 8080:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.nas.lan`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    networks:
      - web
    dns:
      - 127.0.0.1
    restart: always

networks:
  web:
    driver: bridge