version: "3.7"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.0.3
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # volumes:
    #   - ./config/radarr:/config
    #   - ./medias/movies:/movies
    #   - ./downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.nas.lan`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    restart: always
    networks:
      - web

networks:
  web:
    driver: bridge
