---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create the /etc/apt/keyrings directory (if necessary)
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Check permissions of the docker.asc file
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to the APT sources list
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Create Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the current user to the Docker group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Update the session to reflect the group change
  ansible.builtin.shell: newgrp docker || true
  args:
    executable: /bin/bash

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version
  failed_when: docker_version.rc != 0

- name: Install Docker Compose plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present

- name: Verify Docker Compose installation
  ansible.builtin.command: docker compose version
  register: compose_version
  failed_when: compose_version.rc != 0

- name: Find all compose files
  ansible.builtin.find:
    paths: "/home/nas/nas-ansible/services/"
    patterns: "*.yml"
  register: compose_files

- name: Echo the path of each compose file
  ansible.builtin.shell: |
    docker compose -f /home/nas/nas-ansible/services/dockge.yml up -d
  # loop: "{{ compose_files.files }}"
  when: compose_files.files | length > 0
  